2020-11-08 14:24:30,526 INFO    MainThread:25836 [internal.py:wandb_internal():63] W&B internal server running at pid: 25836
2020-11-08 14:24:30,527 INFO    WriterThread:25836 [datastore.py:open_for_write():76] open: wandb\run-20201108_142429-3rl7xsms\run-3rl7xsms.wandb
2020-11-08 14:24:30,527 DEBUG   HandlerThread:25836 [handler.py:handle_request():55] handle_request: check_version
2020-11-08 14:24:30,528 DEBUG   SenderThread:25836 [sender.py:send():90] send: header
2020-11-08 14:24:30,528 DEBUG   SenderThread:25836 [sender.py:send():90] send: request
2020-11-08 14:24:30,528 DEBUG   SenderThread:25836 [sender.py:send_request():99] send_request: check_version
2020-11-08 14:24:30,534 DEBUG   Thread-8  :25836 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): pypi.org:443
2020-11-08 14:24:30,623 DEBUG   Thread-8  :25836 [connectionpool.py:_make_request():433] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 51383
2020-11-08 14:24:30,655 DEBUG   SenderThread:25836 [sender.py:send():90] send: run
2020-11-08 14:24:30,659 INFO    SenderThread:25836 [sender.py:_maybe_setup_resume():280] checking resume status for None/ch-en-try/3rl7xsms
2020-11-08 14:24:30,661 DEBUG   SenderThread:25836 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-08 14:24:30,806 DEBUG   SenderThread:25836 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-08 14:24:30,818 DEBUG   SenderThread:25836 [util.py:is_cygwin_git():315] Failed checking if running in CYGWIN due to: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
2020-11-08 14:24:30,820 DEBUG   SenderThread:25836 [cmd.py:execute():718] Popen(['git', 'cat-file', '--batch-check'], cwd=D:\Academics\Fall 2020\CS 701 Seminar\Bo-Eng-Machine-Transation, universal_newlines=False, shell=None, istream=<valid stream>)
2020-11-08 14:24:30,877 DEBUG   SenderThread:25836 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-08 14:24:31,025 DEBUG   SenderThread:25836 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-08 14:24:31,079 DEBUG   HandlerThread:25836 [handler.py:handle_request():55] handle_request: run_start
2020-11-08 14:24:31,082 INFO    SenderThread:25836 [dir_watcher.py:__init__():164] watching files in: wandb\run-20201108_142429-3rl7xsms\files
2020-11-08 14:24:31,082 INFO    SenderThread:25836 [sender.py:_start_run_threads():487] run started: 3rl7xsms with start time 1604863469
2020-11-08 14:24:31,082 DEBUG   SenderThread:25836 [sender.py:send():90] send: summary
2020-11-08 14:24:31,083 INFO    SenderThread:25836 [sender.py:_save_file():568] saving file wandb-summary.json with policy end
2020-11-08 14:24:31,110 DEBUG   HandlerThread:25836 [cmd.py:execute():718] Popen(['git', 'cat-file', '--batch-check'], cwd=D:\Academics\Fall 2020\CS 701 Seminar\Bo-Eng-Machine-Transation, universal_newlines=False, shell=None, istream=<valid stream>)
2020-11-08 14:24:31,163 DEBUG   HandlerThread:25836 [cmd.py:execute():718] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=D:\Academics\Fall 2020\CS 701 Seminar\Bo-Eng-Machine-Transation, universal_newlines=False, shell=None, istream=None)
2020-11-08 14:24:31,316 DEBUG   SenderThread:25836 [sender.py:send():90] send: files
2020-11-08 14:24:31,316 INFO    SenderThread:25836 [sender.py:_save_file():568] saving file wandb-metadata.json with policy now
2020-11-08 14:24:31,316 DEBUG   HandlerThread:25836 [handler.py:handle_request():55] handle_request: status
2020-11-08 14:24:31,317 DEBUG   SenderThread:25836 [sender.py:send():90] send: request
2020-11-08 14:24:31,317 DEBUG   SenderThread:25836 [sender.py:send_request():99] send_request: status
2020-11-08 14:24:31,320 DEBUG   SenderThread:25836 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-08 14:24:31,325 DEBUG   Thread-17 :25836 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-08 14:24:31,424 DEBUG   SenderThread:25836 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-08 14:24:31,426 DEBUG   SenderThread:25836 [sender.py:send():90] send: config
2020-11-08 14:24:31,430 DEBUG   SenderThread:25836 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-08 14:24:31,439 DEBUG   Thread-17 :25836 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-08 14:24:31,442 DEBUG   Thread-17 :25836 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): storage.googleapis.com:443
2020-11-08 14:24:31,588 DEBUG   SenderThread:25836 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-08 14:24:31,702 DEBUG   HandlerThread:25836 [handler.py:handle_request():55] handle_request: pause
2020-11-08 14:24:31,702 INFO    HandlerThread:25836 [handler.py:handle_request_pause():226] stopping system metrics thread
2020-11-08 14:24:31,731 DEBUG   Thread-17 :25836 [connectionpool.py:_make_request():433] https://storage.googleapis.com:443 "PUT /wandb-production.appspot.com/submalpast/ch-en-try/3rl7xsms/wandb-metadata.json?Expires=1604949871&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=alOWrq56CBG20b%2BKPm4Av7DB%2BgNPC3habnDWle2JGEjoX5t9QNMorbK%2FhtSGHA%2BcZj64qpDXGm5AT7xoSd3dmtNihU1y5wgzKi8dnJHwTaQZ4ZyvNTf09ERZwRwIYEbhpEUgwnoncsK6ljMZJTWUxQRsIchIvcX6a%2FZCsjl7pjAHOQsEgbtP1u%2B1Cx5FEHkH7%2BZaCuhVTr8C1UB1M6RWvEUgB16T4ZJ9f8KGIbyDi3sa2eegXgA4yXMVekAQ6hQ%2BHK2m6YU%2B9YIDe2Jh8S%2BNSllUZtZhL6DTRGEpCLehAu3KAZkGI8Yf3ZXSnEJY%2BV9mtV6bxmdFf%2FPNywBGveOgGA%3D%3D HTTP/1.1" 200 0
2020-11-08 14:24:31,733 INFO    Thread-17 :25836 [upload_job.py:push():131] Uploaded file C:\Users\presu\AppData\Local\Temp\tmpujmy5qg9wandb\3ctorn17-wandb-metadata.json
2020-11-08 14:24:31,832 INFO    HandlerThread:25836 [handler.py:finish():271] shutting down handler
2020-11-08 14:24:32,086 INFO    Thread-12 :25836 [dir_watcher.py:_on_file_modified():225] file/dir modified: wandb\run-20201108_142429-3rl7xsms\files\config.yaml
2020-11-08 14:24:32,086 INFO    Thread-12 :25836 [dir_watcher.py:_on_file_created():212] file/dir created: wandb\run-20201108_142429-3rl7xsms\files\requirements.txt
2020-11-08 14:24:32,087 INFO    Thread-12 :25836 [dir_watcher.py:_on_file_created():212] file/dir created: wandb\run-20201108_142429-3rl7xsms\files\wandb-summary.json
2020-11-08 14:24:32,087 INFO    Thread-12 :25836 [dir_watcher.py:_on_file_created():212] file/dir created: wandb\run-20201108_142429-3rl7xsms\files\output.log
2020-11-08 14:24:32,087 INFO    Thread-12 :25836 [dir_watcher.py:_on_file_created():212] file/dir created: wandb\run-20201108_142429-3rl7xsms\files\wandb-metadata.json
2020-11-08 14:24:32,348 INFO    WriterThread:25836 [datastore.py:close():257] close: wandb\run-20201108_142429-3rl7xsms\run-3rl7xsms.wandb
2020-11-08 14:24:32,549 ERROR   MainThread:25836 [internal.py:wandb_internal():129] Thread SenderThread:
Traceback (most recent call last):
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\internal\internal_util.py", line 33, in run
    self._run()
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\internal\internal_util.py", line 60, in _run
    self._process(record)
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\internal\internal.py", line 233, in _process
    self._sm.send(record)
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\internal\sender.py", line 92, in send
    send_handler(record)
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\internal\sender.py", line 564, in send_config
    config_util.save_config_file_from_dict(config_path, config_dict)
  File "C:\Users\presu\miniconda3\envs\cs701\lib\site-packages\wandb\sdk\lib\config_util.py", line 48, in save_config_file_from_dict
    conf_file.write(data)
  File "C:\Users\presu\miniconda3\envs\cs701\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2581' in position 388: character maps to <undefined>
2020-11-08 14:24:32,569 DEBUG   raven-sentry.BackgroundWorker:25836 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): o151352.ingest.sentry.io:443
2020-11-08 14:24:32,780 DEBUG   raven-sentry.BackgroundWorker:25836 [connectionpool.py:_make_request():433] https://o151352.ingest.sentry.io:443 "POST /api/5288891/store/ HTTP/1.1" 200 41
2020-11-08 14:24:33,442 DEBUG   Thread-9  :25836 [connectionpool.py:_new_conn():939] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-08 14:24:33,582 DEBUG   Thread-9  :25836 [connectionpool.py:_make_request():433] https://api.wandb.ai:443 "POST /files/submalpast/ch-en-try/3rl7xsms/file_stream HTTP/1.1" 200 None
2020-11-08 14:24:34,577 INFO    MainThread:25836 [internal.py:handle_exit():138] Internal process exited
